apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: hello-world-python-pipeline
description: hello-world-python application delivery pipeline
serialPipeline:
 stages:
 - targetId: test
   profiles:
   - staging
 - targetId: staging
   profiles:
   - staging
 - targetId: prod
   profiles:
   - prod


---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: test
description: test cluster
gke:
  cluster: projects/$PROJECT_ID/locations/us-central1/clusters/testcluster
executionConfigs:
  serviceAccount: 7454890225@cloudbuild.gserviceaccount.com
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: staging cluster
gke:
  cluster: projects/$PROJECT_ID/locations/us-central1/clusters/stagingcluster
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: prod cluster
requireApproval: true
gke:
  cluster: projects/$PROJECT_ID/locations/us-central1/clusters/prodcluster